var socaBetABI = [
    { inputs: [], stateMutability: "payable", type: "constructor" },
    {
        anonymous: false,
        inputs: [{
                indexed: false,
                internalType: "address",
                name: "user",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "stakeA",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "stakeB",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "stakeDraw",
                type: "uint256",
            },
        ],
        name: "NewBet",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [{
                indexed: true,
                internalType: "address",
                name: "previousOwner",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "OwnershipTransferred",
        type: "event",
    },
    {
        inputs: [],
        name: "betMin",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        name: "bets",
        outputs: [
            { internalType: "address", name: "user", type: "address" },
            { internalType: "uint256", name: "stakeA", type: "uint256" },
            { internalType: "uint256", name: "stakeB", type: "uint256" },
            { internalType: "uint256", name: "stakeDraw", type: "uint256" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "contractOwner",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "_scoreA", type: "uint256" },
            { internalType: "uint256", name: "_scoreB", type: "uint256" },
        ],
        name: "distributeStake",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "game",
        outputs: [
            { internalType: "string", name: "teamA", type: "string" },
            { internalType: "string", name: "teamB", type: "string" },
            { internalType: "uint256", name: "betStart", type: "uint256" },
            { internalType: "uint256", name: "betEnd", type: "uint256" },
            { internalType: "uint256", name: "oddsA", type: "uint256" },
            { internalType: "uint256", name: "oddsB", type: "uint256" },
            { internalType: "uint256", name: "oddsDraw", type: "uint256" },
            { internalType: "uint256", name: "scoreA", type: "uint256" },
            { internalType: "uint256", name: "scoreB", type: "uint256" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getGameInfoAll",
        outputs: [
            { internalType: "string", name: "", type: "string" },
            { internalType: "string", name: "", type: "string" },
            { internalType: "uint256", name: "", type: "uint256" },
            { internalType: "uint256", name: "", type: "uint256" },
            { internalType: "uint256", name: "", type: "uint256" },
            { internalType: "uint256", name: "", type: "uint256" },
            { internalType: "uint256", name: "", type: "uint256" },
            { internalType: "uint256", name: "", type: "uint256" },
            { internalType: "uint256", name: "", type: "uint256" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "isOwner",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "renounceOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "string", name: "_teamA", type: "string" },
            { internalType: "string", name: "_teamB", type: "string" },
            { internalType: "uint256", name: "_betStart", type: "uint256" },
            { internalType: "uint256", name: "_betEnd", type: "uint256" },
        ],
        name: "setGameInfo",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "_oddsA", type: "uint256" },
            { internalType: "uint256", name: "_oddsB", type: "uint256" },
            { internalType: "uint256", name: "_oddsDraw", type: "uint256" },
        ],
        name: "setGameOdds",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "_scoreA", type: "uint256" },
            { internalType: "uint256", name: "_scoreB", type: "uint256" },
        ],
        name: "setGameScore",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "_stakeA", type: "uint256" },
            { internalType: "uint256", name: "_stakeB", type: "uint256" },
            { internalType: "uint256", name: "_stakeDraw", type: "uint256" },
        ],
        name: "toBet",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "totalMoneyA",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalMoneyB",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalMoneyDraw",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
        name: "transferOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];